language: java
jdk:
- openjdk12
env:
  global:
  - secure: gHX+tJ1loM0+kR6HBAfDB42AeQYrp5mZKyvjmVkjB8V+fqZX8sblXOCpjBEOnXGMVfWmukWElgYlP9LbkQqgh5Dmn5e/iYysmXPiEvYUBu1+IZYS+aYO0+dw/Cd47XhIsMQCeYG/RqKfjFmiaNJarmHzpk97QyiZ+4MxzSbt32YNMKLnWamLaOE2pbYngCpRxG9xkwP350OX6MvQnm6sqadu/u428Zl5MmzpWqPlPPVNBTwo+H0TKATI6ITVSDz+Px1NMD7kKZiDQq5Cx2Te/KWM6H7/9pz4DdCfvgcBisDlc706V+XC1g0tfRzGUQVhVYfN2392/1j4/85xcXpeMXluYgGG0PvaBuCm8pK6bT5hIVDafpOU9MDfLlLtkH0wAtkAiZnL3rWlQDDLgVILy7As7mOTvrcDWuKTmOvQta3vMZQ/AXbAqKY4pTTLXKlf3fq6jzP+ilDCvKuHw9scU84Xz/HfoOzFeW9ZQZLgfjpiLetLEmtquE9ObhjAmPk9UDzIH8zmz87tYujqMzEDWrEPt+3DUwnocLVCQhqMtDtbBagl53w/3U7UGrCnNbuo+6LRl4yt7Qq1rENGe2kVL08pe0MCG8jHxFrsm//9iGUV4RrnasIF8FGKf8lHuQS8lmLknQG2mNCmZPELPphEqhRvbCe4Dj1Mo+Ocjby3VBg=
 
addons:
  sonarcloud:
    organization: "codeaches-github"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar -Dsonar.host.url=https:/sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN}